# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basicDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField()),
                ('wake_up_time', models.TimeField()),
                ('sleep_time', models.TimeField()),
            ],
        ),
    ]
